#!/usr/bin/env bash
# =============================================================================
# docker/init-env.sh
#
# Interactive first-time setup: asks for the three values a human must provide
# (domain, email, DB password) and auto-generates every secret, producing a
# ready-to-use .env file.
#
# Safe to re-run: it will NOT overwrite an existing .env unless you pass --force.
#
# Usage:
#   ./init-env.sh               # interactive
#   ./init-env.sh --force       # overwrite existing .env
#   ROOT_DOMAIN=example.com \
#   MATRIX_DOMAIN=matrix.example.com \
#   ELEMENT_DOMAIN=element.example.com \
#   LIVEKIT_DOMAIN=livekit.example.com \
#   TURN_DOMAIN=turn.example.com \
#   LETSENCRYPT_EMAIL=me@example.com \
#   POSTGRES_PASSWORD=secret \
#   ./init-env.sh               # fully non-interactive (CI / automation)
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
EXAMPLE_FILE="${SCRIPT_DIR}/.env.example"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[init-env]${NC} $*"; }
success() { echo -e "${GREEN}[init-env]${NC} $*"; }
warn()    { echo -e "${YELLOW}[init-env]${NC} $*"; }
die()     { echo -e "${RED}[init-env]${NC} $*" >&2; exit 1; }

FORCE=false
for arg in "$@"; do [[ "$arg" == "--force" ]] && FORCE=true; done

# ── Guard against overwriting an existing .env ────────────────────────────────
if [[ -f "${ENV_FILE}" && "${FORCE}" == false ]]; then
    warn ".env already exists. Use --force to overwrite it."
    exit 0
fi

command -v openssl &>/dev/null || die "openssl is required but not found."

gen_secret() { openssl rand -hex 32; }
gen_short()  { openssl rand -hex 16; }

# ── Collect the three human-provided values ───────────────────────────────────
echo
info "=== Matrix Home Server – Environment Setup ==="
echo
echo "  This script will create your .env with all required secrets."
echo "  You only need to provide three values:"
echo

# Allow non-interactive use via environment variables
if [[ -z "${ROOT_DOMAIN:-}" ]]; then
    read -rp "  1. Your root domain (e.g. example.com): " ROOT_DOMAIN
fi
[[ -z "${ROOT_DOMAIN}" ]] && die "ROOT_DOMAIN cannot be empty."
[[ "${ROOT_DOMAIN}" == *"example.com"* ]] && die "That still looks like the placeholder. Set a real domain."

# Derive service-specific hostnames if not provided explicitly.
MATRIX_DOMAIN="${MATRIX_DOMAIN:-matrix.${ROOT_DOMAIN}}"
ELEMENT_DOMAIN="${ELEMENT_DOMAIN:-element.${ROOT_DOMAIN}}"
LIVEKIT_DOMAIN="${LIVEKIT_DOMAIN:-livekit.${ROOT_DOMAIN}}"
TURN_DOMAIN="${TURN_DOMAIN:-turn.${ROOT_DOMAIN}}"

if [[ -z "${LETSENCRYPT_EMAIL:-}" ]]; then
    read -rp "  2. Your email for Let's Encrypt notifications: " LETSENCRYPT_EMAIL
fi
[[ -z "${LETSENCRYPT_EMAIL}" ]] && die "LETSENCRYPT_EMAIL cannot be empty."

if [[ -z "${POSTGRES_PASSWORD:-}" ]]; then
    read -rsp "  3. Database password (leave blank to auto-generate): " POSTGRES_PASSWORD
    echo
fi
# Auto-generate database password if not provided
if [[ -z "${POSTGRES_PASSWORD}" ]]; then
    POSTGRES_PASSWORD="$(gen_secret)"
    info "Auto-generated database password."
fi

# ── Generate all secrets ──────────────────────────────────────────────────────
info "Generating secrets…"
REGISTRATION_SHARED_SECRET="$(gen_secret)"
MACAROON_SECRET_KEY="$(gen_secret)"
FORM_SECRET="$(gen_secret)"
COTURN_SECRET="$(gen_secret)"
LIVEKIT_API_KEY="$(gen_short)"
LIVEKIT_API_SECRET="$(gen_secret)"

# ── Write .env ────────────────────────────────────────────────────────────────
cat > "${ENV_FILE}" <<EOF
# =============================================================================
# docker/.env  –  generated by init-env.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
# NEVER commit this file to version control – it contains secrets.
# To regenerate: rm .env && ./init-env.sh
# =============================================================================

# ── Domains ───────────────────────────────────────────────────────────────────
ROOT_DOMAIN=${ROOT_DOMAIN}
MATRIX_DOMAIN=${MATRIX_DOMAIN}
ELEMENT_DOMAIN=${ELEMENT_DOMAIN}
LIVEKIT_DOMAIN=${LIVEKIT_DOMAIN}
TURN_DOMAIN=${TURN_DOMAIN}
LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

# ── Synapse secrets ───────────────────────────────────────────────────────────
REGISTRATION_SHARED_SECRET=${REGISTRATION_SHARED_SECRET}
MACAROON_SECRET_KEY=${MACAROON_SECRET_KEY}
FORM_SECRET=${FORM_SECRET}

# ── PostgreSQL ────────────────────────────────────────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_USER=synapse
POSTGRES_DB=synapse

# ── coturn TURN server ────────────────────────────────────────────────────────
COTURN_SECRET=${COTURN_SECRET}

# ── LiveKit SFU ───────────────────────────────────────────────────────────────
LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}

# ── Deployment flags ──────────────────────────────────────────────────────────
# Set to "true" once you have SSL certificates via ./init-letsencrypt.sh.
SSL_ENABLED=false
EOF

chmod 600 "${ENV_FILE}"

success ".env created at ${ENV_FILE}"
echo
echo "  Next step: run  ./deploy.sh"
echo
